@endpoint = https://qoe8b3qb2k.execute-api.us-west-2.amazonaws.com/prod

// GET - all spaces
GET {{endpoint}}/spaces/
###

//GET - space with ID: 8bd4a9e4-380a-4b83-bf74-90d3d22d9409
GET {{endpoint}}/spaces?spaceId=8bd4a9e4-380a-4b83-bf74-90d3d22d9409
###

//GET - spaces in ?location=Victoria
GET {{endpoint}}/spaces?location=Victoria
###

//PUT - update space with new details
PUT {{endpoint}}/spaces?spaceId=8bd4a9e4-380a-4b83-bf74-90d3d22d9409
Content-Type: application/json

{
    "location": "Vancouver",
    "field1": "VFMP details"
}
###

//POST - create a new space with the following details
POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Victoria",
    "name": "MSB 160",
    "field1": "Additional data field"
}
###

//POST - to test input validation; missing name
POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Victoria",
    "field1": "Additional data field"
}
###

//POST - to test input validation; missing location
POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "name": "NHSC 110 LT",
    "field1": "Additional data field"
}
###

//DELETE - removes item with ?spaceId
DELETE {{endpoint}}/spaces?spaceId=56d22688-7523-4ff5-9b03-1fd26a4aaae2
###
